"""Human-written round-trip tests (v2.7).

Per swarm empirical-critic finding: the existing roundtrip tests verify
``emit ∘ parse ∘ emit ≡ emit`` — i.e. the parser inverts the emitter on
emitter outputs. That is necessary but not sufficient. The property a
production parser actually needs is:

    parse(human_written_atm) → LoweredDecl[] that re-emits to the same text

The natural test corpus for this is `.atm` text written BY HAND — not
text generated by the lowerer that the parser is being trained on. This
file holds hand-curated `.atm` declarations and verifies they survive
parser round-trip.
"""

from __future__ import annotations

import pytest

from atomadic_lang.a1_at_functions.atm_emit import emit_module
from atomadic_lang.a1_at_functions.atm_parse import parse_decl, parse_module


# --- representative hand-written single decls ----------------------------

# Each tuple: (name, atm_text, expected_top_level_property_to_check)
HAND_WRITTEN_DECLS: list[tuple[str, str, dict]] = [
    ("inline_arith",
     "1π add ⟨a:i b:i⟩→i = a+b",
     {"tier": 1, "effect": "π", "name": "add", "body_form": "inline"}),

    ("inline_with_complex_body",
     '1π render ⟨name:s⟩→s = s"hello ⟦name⟧"',
     {"tier": 1, "effect": "π", "name": "render", "body_form": "inline"}),

    ("class_record",
     "0 ScoutReport ⟨schema:s file_count:i symbols:[_]⟩",
     {"tier": 0, "name": "ScoutReport", "body_form": "class"}),

    ("class_with_field_inferred",
     "2σ Counter ⟨value:i⟩",
     {"tier": 2, "effect": "σ", "name": "Counter", "body_form": "class"}),

    ("dotted_method",
     "2σ Counter.increment ⟨self:Counter⟩→∅ = (self.value=self.value+1 ; ∅)",
     {"tier": 2, "name": "Counter.increment", "body_form": "inline"}),

    ("tier_0_constant",
     "0 EPS : f = 1e-9",
     {"tier": 0, "name": "EPS", "return_sigil": "f"}),

    ("optional_return",
     "1π lookup ⟨k:s⟩→?s = ∅",
     {"tier": 1, "name": "lookup", "return_sigil": "?s", "body_form": "inline"}),

    ("list_of_records",
     "0 Manifest ⟨items:[_] count:i⟩",
     {"tier": 0, "name": "Manifest", "body_form": "class"}),

    ("a4_io_entry",
     "4ι main ⟨⟩→_ = (parse-args() ; print(\"hi\") ; ∅)",
     {"tier": 4, "effect": "ι", "name": "main", "body_form": "inline"}),

    ("with_comprehension",
     "1π squares ⟨xs:[i]⟩→[i] = [x*x | x∈xs]",
     {"tier": 1, "name": "squares", "body_form": "inline"}),

    ("with_lambda",
     "1π double_all ⟨xs:[i]⟩→[i] = list(map(x↦x*2,xs))",
     {"tier": 1, "name": "double_all", "body_form": "inline"}),
]


@pytest.mark.parametrize("name,text,expected", HAND_WRITTEN_DECLS, ids=[t[0] for t in HAND_WRITTEN_DECLS])
def test_hand_written_decl_parses_with_expected_structure(name: str, text: str, expected: dict) -> None:
    """Each hand-written line must parse and recover the expected structure."""
    d = parse_decl(text)
    assert d is not None, f"failed to parse: {text!r}"
    for key, want in expected.items():
        got = d[key]  # type: ignore[literal-required]
        assert got == want, (
            f"{name}: expected {key}={want!r}, got {got!r} (full decl: {d})"
        )


@pytest.mark.parametrize("name,text,_expected", HAND_WRITTEN_DECLS, ids=[t[0] for t in HAND_WRITTEN_DECLS])
def test_hand_written_decl_round_trips(name: str, text: str, _expected: dict) -> None:
    """Each hand-written line should parse → emit → identical text."""
    d = parse_decl(text)
    assert d is not None, f"failed to parse: {text!r}"
    re_emitted = emit_module("p", [d])
    # Strip the @p header + blank line for single-decl comparison
    body_only = re_emitted.replace("@p\n\n", "", 1).rstrip("\n")
    assert body_only == text, (
        f"{name} round-trip diverged:\n"
        f"  original: {text!r}\n"
        f"  re-emitted: {body_only!r}"
    )


# --- multi-decl hand-written modules -------------------------------------


def test_hand_written_module_round_trips() -> None:
    """A multi-decl hand-written module should fully round-trip."""
    text = (
        "@hand\n"
        "\n"
        "0 EPS : f = 1e-9\n"
        "0 OP = enum{+,-,*,/}\n"
        "\n"
        "1π add ⟨a:i b:i⟩→i = a+b\n"
        "1π divide ⟨a:i b:i⟩→f\n"
        "  pre b≠0\n"
        "  body a/b\n"
        "\n"
        "2σ Counter ⟨value:i⟩\n"
        "2σ Counter.get ⟨self:Counter⟩→i = self.value\n"
    )
    mod = parse_module(text)
    re_emitted = emit_module(mod["package"], mod["decls"])
    assert mod["package"] == "hand"
    assert len(mod["decls"]) == 6
    # Round-trip property: re-emitted text should be byte-identical.
    assert re_emitted == text, (
        f"hand-written module did not round-trip:\n"
        f"---original---\n{text!r}\n"
        f"---re-emitted---\n{re_emitted!r}"
    )


def test_hand_written_refinement_form_specific_fields() -> None:
    """The refinement form specifically should preserve pre/body across parse."""
    text = "1π safe_div ⟨a:i b:i⟩→f"
    cont = ["  pre b≠0", "  body a/b"]
    d = parse_decl(text, cont)
    assert d is not None
    assert d["body_form"] == "refinement"
    assert d["pre"] == "b≠0"
    assert d["body"] == "a/b"
    assert d["return_sigil"] == "f"


def test_unparseable_input_does_not_crash() -> None:
    """Garbage input should return a sentinel, not raise an exception."""
    # Lines with non-tier-digit start should be silently skipped.
    bad = "@p\n\nthis is not .atm syntax\n5x not a tier digit\n"
    mod = parse_module(bad)
    assert mod["package"] == "p"
    # No valid decls extractable.
    assert mod["decls"] == []


def test_unicode_and_ascii_effect_sigils() -> None:
    """Both Unicode (π) and the bare-tier (no sigil) forms should parse."""
    # Unicode form
    d_u = parse_decl("1π add ⟨a:i b:i⟩→i = a+b")
    assert d_u is not None
    assert d_u["effect"] == "π"
    # Bare tier (no effect sigil) — should be permitted; effect defaults.
    d_b = parse_decl("1 noeffect ⟨a:i⟩→i = a")
    assert d_b is not None
    # Default-effect logic in parser fills tier-1's default effect (π).
    assert d_b["effect"] in ("", "π")
